
CREATE TABLESPACE DEVELOPMENT DATAFILE '/u01/app/oracle/oradata/XE/development.dbf' SIZE 100M AUTOEXTEND ON;

CREATE USER DEVELOPMENT IDENTIFIED BY development DEFAULT TABLESPACE "DEVELOPMENT";
GRANT connect, resource TO DEVELOPMENT;

GRANT create session TO DEVELOPMENT;
GRANT CREATE TABLE TO DEVELOPMENT;
GRANT CREATE SEQUENCE TO DEVELOPMENT;
GRANT CREATE TABLE TO DEVELOPMENT;
GRANT UNLIMITED TABLESPACE TO DEVELOPMENT;

CREATE TABLESPACE TESTING DATAFILE '/u01/app/oracle/oradata/XE/testing.dbf' SIZE 100M AUTOEXTEND ON;

CREATE USER TEST IDENTIFIED BY test DEFAULT TABLESPACE "TESTING";
GRANT connect, resource TO TESTING;

GRANT create session TO TEST;
GRANT CREATE TABLE TO TEST;
GRANT CREATE SEQUENCE TO TEST;
GRANT CREATE TABLE TO TEST;
GRANT UNLIMITED TABLESPACE TO TEST;

